### ISSUE TITLE
Change HTTP status code to 301 Moved Permanently or allow configuration

### ISSUE THREAD

**Issue by dboehmer** [papercreatures/Catalyst-ActionRole-RequireSSL#1]
This module doesn't explicitly set the HTTP status code and the default for `$c->res->direct()` is 302 Found.

As this role is applied to actions at development time the redirect is somewhat permanent and should explicitly set the HTTP response status code to 301 Moved Permanently.

Alternative or additional idea: add a config option like `http_response_code` to allow the app to control the code.

Unfortunately can't be easily modified because this module uses `$c->detach` the exit the action chain.

**Comment by dboehmer** [comment]
@purge You also seem to have permissions on this repo and upload permissions for CPAN. Do you consider picking this up?

I'd also post a PR if we'd agree on just changing the status code or adding a config option.

**Comment by wreis** [comment]
On 04/02/2018 16:40, Daniel Böhmer wrote:
> @purge <https://github.com/purge> You also seem to have permissions on 
> this repo and upload permissions for CPAN. Do you consider picking this up?
> 
> I'd also post a PR if we'd agree on just changing the status code or 
> adding a config option.

Please send a PR with tests for the config option, and I will be happy 
to merge.

Cheers,

-- 
Wallace Reis

**Comment by purge** [comment]
Sorry just seen this - yeah that is a bug, happy with a PR for 301 to fix it
